# -*- coding: utf-8 -*-
"""DowJonesMatrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CRPeX4JpxKgMuvnsW9px3QH0bYmd5DaJ
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import streamlit as st

df = pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')[1]
tickers = df.Symbol.to_list()

infos = []

for i in tickers:
  infos.append(yf.Ticker(i).info)

df = pd.DataFrame(infos)

df = df.set_index('symbol')

df

fig = px.scatter(df,
           title='Company Valuation Matrix',
           template='simple_white',
           x='priceToBook',
                y='trailingPE',
                color='shortName',
           size='revenuePerShare',
           hover_data=['dividendYield', 'previousClose']
           )

fig.show()