# -*- coding: utf-8 -*-
"""FundamentalDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRFa3K-DOgNBjGl3lrGeZNRWWi1rxvCn
"""

pip install streamlit yfinance

import sqlalchemy
import streamlit as st
import yfinance as yf
import pandas as pd

st.write("""
# Financial Dashboard
""")

tickers = pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')[1]
tickers = tickers.Symbol.to_list()

df = pd.DataFrame()

for ticker in tickers:
    var = yf.Ticker(ticker).info
    frame = pd.DataFrame([var])
    df = df.append(frame)

engine = sqlalchemy.create_engine('sqlite:///Fundamentals.db')

subdf = df[['symbol', 'sector', 'trailingPE' ,'dividendYield', 'priceToBook']]

subdf.to_sql('Fundamentalstable',engine,index=False)

pd.read_sql('Fundamentalstable', engine, index_col=['symbol'])

st.title('Fundamentals')

engine = sqlalchemy.create_engine('sqlite:///Fundamentals.db')

df = pd.read_sql('Fundamentalstable', engine, index_col=['symbol'])

dropdownI = st.selectbox('choose your sector',df.sector.unique())

dropdownII = st.selectbox('choose your matrix', df.columns[df.columns !='sector'])

values = df[df.sector == dropdownI][[dropdownII]]

st.bar_chart(values)