# -*- coding: utf-8 -*-
"""StreamlitChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZIlIEqfUu0zZu-k7HjL2WpqFMFomPf9
"""

!pip install streamlit

!pip install yfinance

import yfinance as yf
import streamlit as st
import pandas as pd

# Here you can use markdown language to make your app prettier
st.write("""
# Financial App
""")

# We will use Amazon stocks
stock = 'AMZN'

# Get stock data
get_stock_data = yf.Ticker(stock)

# Set the time line of your data
ticket_df = get_stock_data.history(period='1d', start='2010-1-02', end='2022-6-10')

# Show your data in line chart
st.line_chart(ticket_df.Close)
st.line_chart(ticket_df.Volume)